"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { BrainCircuit, ChevronLeft, ChevronRight, HelpCircle, Lightbulb, ThumbsUp } from "lucide-react"

interface Question {
  id: string
  text: string
  options: string[]
  correctAnswer: number
  difficulty: "easy" | "medium" | "hard"
  explanation: string
}

export default function AdaptiveLearningEngine() {
  // In a real app, these would be dynamically generated by AI based on user performance
  const [questions, setQuestions] = useState<Question[]>([
    {
      id: "q1",
      text: "What is the primary purpose of a blockchain?",
      options: [
        "To store large amounts of data",
        "To create a decentralized, immutable ledger",
        "To speed up database queries",
        "To encrypt all online communications",
      ],
      correctAnswer: 1,
      difficulty: "easy",
      explanation:
        "A blockchain is fundamentally a decentralized, immutable ledger that records transactions across many computers so that the record cannot be altered retroactively.",
    },
    {
      id: "q2",
      text: "Which of these is a characteristic of blockchain technology?",
      options: [
        "Centralized control",
        "Easy modification of past records",
        "Transparency and tamper resistance",
        "Low computational requirements",
      ],
      correctAnswer: 2,
      difficulty: "easy",
      explanation:
        "Blockchain provides transparency since all network participants can see the same ledger, and it's tamper-resistant due to its cryptographic linking of blocks.",
    },
    {
      id: "q3",
      text: "What cryptographic technique is used to secure blocks in a blockchain?",
      options: ["AES Encryption", "Hash Functions", "RSA Encryption", "Simple Password Protection"],
      correctAnswer: 1,
      difficulty: "medium",
      explanation:
        "Hash functions convert data into a fixed-size string of characters. In blockchain, each block contains the hash of the previous block, creating a secure chain.",
    },
    {
      id: "q4",
      text: "In a proof-of-work consensus mechanism, what are miners competing to do?",
      options: [
        "Solve complex mathematical puzzles",
        "Create the most new accounts",
        "Store the most data",
        "Connect to the most peers",
      ],
      correctAnswer: 0,
      difficulty: "medium",
      explanation:
        "In proof-of-work, miners compete to solve computationally difficult puzzles. The first to solve it gets to add a new block to the chain and receives a reward.",
    },
    {
      id: "q5",
      text: "What is the relationship between a public key and a private key in blockchain?",
      options: [
        "They are identical copies of each other",
        "The public key can derive the private key",
        "The private key generates the public key, but not vice versa",
        "They have no mathematical relationship",
      ],
      correctAnswer: 2,
      difficulty: "hard",
      explanation:
        "In asymmetric cryptography used in blockchain, the private key generates the public key through a one-way function. It's computationally infeasible to derive the private key from the public key.",
    },
  ])

  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0)
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null)
  const [answered, setAnswered] = useState(false)
  const [correctAnswers, setCorrectAnswers] = useState(0)
  const [quizCompleted, setQuizCompleted] = useState(false)
  const [showHint, setShowHint] = useState(false)
  const [difficulty, setDifficulty] = useState<"easy" | "medium" | "hard">("easy")
  const [adaptiveMessage, setAdaptiveMessage] = useState("")

  const currentQuestion = questions[currentQuestionIndex]

  // This would be connected to an actual AI service in a real application
  const getAIHint = (question: Question) => {
    const hints = {
      easy: "Think about the fundamental purpose of distributed ledger technology.",
      medium:
        "Consider how data integrity is maintained across a distributed network and what cryptographic techniques enable this.",
      hard: "Think about the mathematical relationships in asymmetric cryptography and how they enable secure transactions without revealing private keys.",
    }

    return hints[question.difficulty] || "Consider the core principles of blockchain technology."
  }

  // Simulate AI adapting to user performance
  useEffect(() => {
    if (quizCompleted) {
      const performance = (correctAnswers / questions.length) * 100

      if (performance > 80) {
        setAdaptiveMessage(
          "Based on your excellent performance, we recommend advancing to more complex blockchain topics like smart contracts and advanced cryptography.",
        )
        setDifficulty("hard")
      } else if (performance > 50) {
        setAdaptiveMessage(
          "You're doing well! We suggest focusing more on consensus mechanisms and blockchain architecture.",
        )
        setDifficulty("medium")
      } else {
        setAdaptiveMessage(
          "Let's reinforce your blockchain fundamentals before moving forward. We've recommended some additional resources for you.",
        )
        setDifficulty("easy")
      }
    }
  }, [quizCompleted, correctAnswers, questions.length])

  const handleAnswer = (answerIndex: number) => {
    setSelectedAnswer(answerIndex)
    setAnswered(true)

    if (answerIndex === currentQuestion.correctAnswer) {
      setCorrectAnswers(correctAnswers + 1)
    }
  }

  const handleNextQuestion = () => {
    setSelectedAnswer(null)
    setAnswered(false)
    setShowHint(false)

    if (currentQuestionIndex < questions.length - 1) {
      setCurrentQuestionIndex(currentQuestionIndex + 1)
    } else {
      setQuizCompleted(true)
    }
  }

  const handlePreviousQuestion = () => {
    if (currentQuestionIndex > 0) {
      setCurrentQuestionIndex(currentQuestionIndex - 1)
      setSelectedAnswer(null)
      setAnswered(false)
      setShowHint(false)
    }
  }

  const resetQuiz = () => {
    setCurrentQuestionIndex(0)
    setSelectedAnswer(null)
    setAnswered(false)
    setCorrectAnswers(0)
    setQuizCompleted(false)
    setShowHint(false)
  }

  if (quizCompleted) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center">
            <BrainCircuit className="mr-2 h-5 w-5 text-red" />
            Adaptive Assessment Complete
          </CardTitle>
          <CardDescription>Your performance has been analyzed by our AI engine</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="text-center py-4">
            <div className="rounded-full bg-yellow-light p-3 mb-4">
              <ThumbsUp className="h-12 w-12 text-yellow-600" />
            </div>
            <h3 className="text-xl font-bold text-yellow-600 mb-2">Congratulations!</h3>
            <p className="text-muted-foreground mt-1">
              {Math.round((correctAnswers / questions.length) * 100)}% accuracy
            </p>
          </div>

          <Progress value={(correctAnswers / questions.length) * 100} className="h-2" />

          <Alert className="mt-4">
            <Lightbulb className="h-4 w-4" />
            <AlertTitle>AI Recommendation</AlertTitle>
            <AlertDescription>{adaptiveMessage}</AlertDescription>
          </Alert>

          <div className="pt-4 flex justify-between">
            <Button variant="outline" onClick={resetQuiz}>
              Restart Quiz
            </Button>
            <Button>Continue Learning Path</Button>
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex justify-between items-center">
          <CardTitle className="flex items-center">
            <BrainCircuit className="mr-2 h-5 w-5 text-primary" />
            Adaptive Quiz: Blockchain Basics
          </CardTitle>
          <div className="text-sm text-muted-foreground">
            Question {currentQuestionIndex + 1} of {questions.length}
          </div>
        </div>
        <CardDescription>This quiz adapts to your knowledge level</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="mb-6">
          <Progress value={(currentQuestionIndex / questions.length) * 100} className="h-2" />
        </div>

        <div>
          <h3 className="text-lg font-medium mb-4">{currentQuestion.text}</h3>

          <div className="space-y-2">
            {currentQuestion.options.map((option, index) => (
              <button
                key={index}
                className={`w-full text-left p-3 rounded-md border transition-colors ${
                  selectedAnswer === index
                    ? answered
                      ? index === currentQuestion.correctAnswer
                        ? "bg-green-100 border-green-300 text-green-800"
                        : "bg-red-100 border-red-300 text-red-800"
                      : "bg-primary/10 border-primary/30 text-primary"
                    : "hover:bg-muted"
                }`}
                onClick={() => !answered && handleAnswer(index)}
                disabled={answered}
              >
                <div className="flex items-start">
                  <div className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full border mr-2 mt-0.5">
                    {selectedAnswer === index && <div className="h-2.5 w-2.5 rounded-full bg-current" />}
                  </div>
                  <span>{option}</span>
                </div>
              </button>
            ))}
          </div>

          {answered && (
            <div className="mt-4 p-3 bg-muted rounded-md text-sm">
              <p className="font-medium mb-1">Explanation:</p>
              <p>{currentQuestion.explanation}</p>
            </div>
          )}

          {!answered && !showHint && (
            <Button variant="ghost" className="mt-4" onClick={() => setShowHint(true)}>
              <HelpCircle className="mr-2 h-4 w-4" />
              Get a hint
            </Button>
          )}

          {!answered && showHint && (
            <div className="mt-4 p-3 bg-blue-light text-blue-700 rounded-md text-sm">
              <p className="font-medium mb-1">AI Hint:</p>
              <p>{getAIHint(currentQuestion)}</p>
            </div>
          )}
        </div>

        <div className="pt-4 flex justify-between">
          <Button variant="outline" onClick={handlePreviousQuestion} disabled={currentQuestionIndex === 0}>
            <ChevronLeft className="mr-2 h-4 w-4" />
            Previous
          </Button>

          {answered ? (
            <Button onClick={handleNextQuestion}>
              {currentQuestionIndex < questions.length - 1 ? (
                <>
                  Next
                  <ChevronRight className="ml-2 h-4 w-4" />
                </>
              ) : (
                "Complete Quiz"
              )}
            </Button>
          ) : (
            <Button disabled>{currentQuestionIndex < questions.length - 1 ? "Next" : "Complete Quiz"}</Button>
          )}
        </div>
      </CardContent>
    </Card>
  )
}
