import { Card, CardContent } from "@/components/ui/card"
import { Gem } from "lucide-react"

export default function RecommendedCourses() {
  // In a real application, these would be fetched from your API and generated by AI
  const recommendations = [
    {
      title: "Smart Contract Development",
      description: "Based on your blockchain interest",
      difficulty: "Intermediate",
      tokens: 30,
      image: "/placeholder.svg?height=80&width=120",
    },
    {
      title: "Data Science for AI",
      description: "Complements your ML courses",
      difficulty: "Advanced",
      tokens: 45,
      image: "/placeholder.svg?height=80&width=120",
    },
    {
      title: "UI/UX for Web3",
      description: "Perfect after your HTML course",
      difficulty: "Beginner",
      tokens: 20,
      image: "/placeholder.svg?height=80&width=120",
    },
  ]

  return (
    <div className="space-y-3">
      {recommendations.map((course, index) => (
        <Card key={index} className="overflow-hidden">
          <CardContent className="p-0">
            <div className="flex">
              <img
                src={course.image || "/placeholder.svg"}
                alt={course.title}
                className="h-auto w-20 object-cover sm:w-24 md:w-32"
              />
              <div className="flex flex-1 flex-col justify-between p-3">
                <div>
                  <h3 className="font-medium">{course.title}</h3>
                  <p className="text-xs text-muted-foreground">{course.description}</p>
                </div>
                <div className="mt-2 flex items-center justify-between">
                  <span className="text-xs bg-primary/10 text-primary px-2 py-1 rounded-full">{course.difficulty}</span>
                  <div className="flex items-center gap-1">
                    <Gem className="h-3 w-3 text-primary" />
                    <span className="text-xs">{course.tokens} tokens</span>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  )
}
